import stylesProductPage from "../../styles/ProductPage.module.css";
import { products } from "../../data";
import Head from "next/head";

const product = ({ product }) => {
  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous"
        />
      </Head>
      <div className={stylesProductPage.container}>
        <h2>{product.productName}</h2>
        <p>{product.productDescription}</p>
        <img
          className={stylesProductPage.productImg}
          src={`../${product.productImg}`}
          alt=""
        />
      </div>
    </div>
  );
};

export default product;

export async function getStaticProps(context) {
  const product = products.filter(
    (product) => product.productName === context.params.product
  )[0];
  return {
    props: { product }, // will be passed to the page component as props
  };
}

export const getStaticPaths = () => {
  const productNames = products.map((product) => product.productName);

  const paths = productNames.map((productName) => ({
    params: { product: productName.toString() },
  }));
  return {
    paths,
    fallback: false,
  };
};
