import Head from "next/head";
import BlogCard from "../components/BlogCard";

const blog = ({ mediumPosts }) => {
  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous"
        />
      </Head>
      <div style={{ margin: "50px" }}>
        <h2>Confira nossos posts no Medium!</h2>

        {mediumPosts.items.map((post, idx) => (
          <BlogCard
            key={idx}
            link={post.guid}
            title={post.title}
            date={post.pubDate.split(" ")[0]}
          />
        ))}
      </div>
    </div>
  );
};

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@microforge"
  );
  const mediumPosts = await res.json();
  return {
    props: {
      mediumPosts,
    },
  };
};

export default blog;
