import Head from 'next/head'
import Slider from '../components/Slider'
import Infos from '../components/Infos'
import Statements from '../components/Statements'
import { server } from '../config'


const index = ({ allNews }) => {
  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous" />
      </Head>

      <Slider allNews={allNews} />

      <Infos />

      <Statements />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/carouselNews`)
  const allNews = await res.json()

  return {
    props: {
      allNews,
    },
  }
}

export default index
