import Head from 'next/head'
import Slider from '../components/Slider'
import Infos from '../components/Infos'
import Statements from '../components/Statements'

const index = () => {
  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
      </Head>

      <Slider />

      <Infos />

      <Statements />
    </div>
  )
}

export default index
