import Head from "next/head";
import Slider from "../components/Slider";
import Infos from "../components/Infos";
import Statements from "../components/Statements";

const index = ({}) => {
  const allNews = [
    {
      id: "1",
      title: "Estamos na Liga Brasileira de Bioinformática!",
      excerpt: "Confira nosso post de apresentação",
      text: " ",
      link: "https://www.instagram.com/p/CP69pGipI8w/?utm_source=ig_web_copy_link",
    },

    {
      id: "1",
      title:
        "Nossa seção de produtos vai ser diferente de tudo o que você já viu",
      excerpt: "Visite a aba de produtos a partir de 20/06",
      text: " ",
      link: "/products",
    },
  ];
  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous"
        />
      </Head>

      <Slider allNews={allNews} />

      <Infos />

      <Statements />
    </div>
  );
};

export default index;
