import Head from "next/head";
import FluxGroup from "../components/FluxGroup";

const products = ({}) => {
  const fluxes = [
    {
      id: "1",
      fluxTitle: "PCR",
      fluxComponents: [
        {
          id: "1",
          componentName: "Extração",
          componentImg: "extraction.jpg",
          componentProducts: ["Linha Sabiá"],
        },
        {
          id: "2",
          componentName: "PCR",
          componentImg: "pcr.jpg",
          componentProducts: [],
        },
        {
          id: "3",
          componentName: "Eletroforese",
          componentImg: "gel.jpg",
          componentProducts: ["Linha Sabiá"],
        },
        {
          id: "4",
          componentName: "RT-qPCR",
          componentImg: "rtpcr.jpg",
          componentProducts: [],
        },
      ],
    },
  ];

  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous"
        />
      </Head>
      <h2 style={{ marginLeft: "50px" }}>
        Escolha um fluxo para ver nossos produtos disponíveis
      </h2>
      <div>
        {fluxes.map((flux) => (
          <FluxGroup key={flux.id} flux={flux} />
        ))}
      </div>
    </div>
  );
};
export default products;
