import Head from 'next/head'
import ProductList from '../components/ProductList'
import { server } from '../config'

const products = ({ products }) => {
  return (
    <div>
      <Head>
        <title>μForge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_microForge.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous" />
      </Head>
      <ProductList products={products} />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/products`)
  const products = await res.json()

  return {
    props: {
      products,
    },
  }
}

export default products
